PostBoard/PostBoard/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.conf import settings
from PostBoard_main import views
from ckeditor_uploader.views import upload, browse, ImageUploadView
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('enter/', views.enter),
    path('posts/', include('PostBoard_main.urls')),
    path('accounts/', include("allauth.urls")),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^upload/', login_required(upload), name='ckeditor_upload'),
    re_path(r'^browse/', login_required(never_cache(browse)), name='ckeditor_browse'),
] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
) + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

PostBoard/PostBoard_main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.utils.translation import gettext as _
from ckeditor_uploader.fields import RichTextUploadingField


class RegUsers(models.Model):
    reg_user = models.OneToOneField(User,  on_delete=models.CASCADE)
    code = models.CharField(max_length=6, blank=True, null=True, default=None)


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True, help_text=_('Category name'))
    subscriber = models.ManyToManyField(User, through='Subscriptions')

    def __str__(self):
        return self.name.title()


class Posts(models.Model):
    tanks = 'TK'
    healers = 'HL'
    damage_dealers = 'DD'
    merchants = 'MR'
    guild_masters = 'GM'
    quest_givers = 'QG'
    smiths = 'SM'
    leather_workers = 'LW'
    potion_masters = 'PM'
    enchanters = 'EH'

    TYPE = [
        (tanks, 'Танки'), (healers, 'Хилеры'), (damage_dealers, 'ДД'), (merchants, 'Торговцы'),
        (guild_masters, 'Гильдмастера'), (quest_givers, 'Квестгиверы'), (smiths, 'Кузнецы'),
        (leather_workers, 'Кожевники'), (potion_masters, 'Зельевары'), (enchanters, 'Мастера заклинаний')
    ]

    type_post = models.CharField(max_length=2, choices=TYPE, default='MR', verbose_name='Время публикации')
    time_in = models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')
    # updated = models.DateTimeField(auto_now=True)  Сюда суется время последнего обновления поста
    headline = models.CharField(max_length=128, verbose_name='Заголовок')
    text = RichTextUploadingField(config_name='my-toolbar', verbose_name='Текст')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category', verbose_name='Категория')
    to_reg_user = models.ForeignKey(RegUsers, on_delete=models.CASCADE, verbose_name='Автор')

    def __str__(self):
        return self.headline

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class Response(models.Model):
    time_in = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    res_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reply_user', verbose_name='Автор')
    res_post = models.ForeignKey(Posts, on_delete=models.CASCADE, related_name='reply', verbose_name='Пост')
    status = models.BooleanField(default=False)

    def __str__(self):
        return 'Response by {} on {}'. format(self.res_user, self.res_post)

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.res_post.id)])


class Subscriptions(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    to_category = models.ForeignKey(
        to=Category,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )





PostBoard/templates/enter.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
      Вход
      {% endblock title%}
    </title>
</head>
<body>
{% block content %}
    <br>
    <h2>Добро пожаловать на доску объявления "Какой-то ММО РПГ"!</h2>
    <h4><a href="{% url 'posts' %}"> На доске </a> вы можете посмотреть объявления.
        Однако что бы иметь возможность писать объявления или оставлять отклика, вам нужно...</h4>
    <button>
        <a class="nav-link" href="{% url 'register' %}">
            <h4><strong>Зарегистрироваться</strong></h4>
        </a>
    </button>
    <br>
    <br>
    <h4>Если у вас уже есть созданный аккаунт то просто...</h4>
    <button>
        <a class="nav-link" href="{% url 'login' %}">
            <h4><strong>Залогиньтесь</strong></h4>
        </a>
    </button>
{% endblock content%}
</body>
</html>

PostBoard/templates/post_create.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}


{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save" />
</form>
{% endblock content %}

PostBoard/templates/post_delete.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  <p>Удаляем "{{ object.headline }}"?</p>
  <input type="submit" value="Delete" />
</form>
{% endblock content %}

PostBoard/templates/post_detail.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Bare - Start Bootstrap Template</title>
    <style type="text/css">
        .body {
        max-width: 1000px;
        }

        TD {
        vertical-align: center;
        padding: 5px;
        }

        TD#leftcol {
        float: center;
        width: 1250px;
        }

        TD#rightcol {
        border-left: 1px solid #000;
        float: center;
        width: 750px;
        }

        .line {
        boeder-left: 1px solid black;
        <h1>!</h1>
        }

    </style>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
            {% if not request.user.is_authenticated %}
            <div class="container">
                <a class="navbar-brand" href="#">Вы вошли как Гость</a>
            </div>
                {% endif %}
                {% if request.user.is_authenticated %}
            <div class="container">
                <a class="navbar-brand" href="#">Вы вошли как {{ request.user }}</a>
            </div>
            <div>
                <a class="navbar-brand" href="{% url 'account_logout' %}">Выйти</a>
            </div>
                {% endif %}
    </nav>
        <table>
            <tr>
                <td id="leftcol">
                    <div class="body">
                        <table>
                            <tr>
                                <th>
                                    <h4>{{ post.headline }} <br> {{ post.time_in|date:'d M Y' }} <br> от {{ post.to_reg_user.reg_user }}</h4>
                                </th>
                            </tr>
                            <tr>
                                <td><h5>{{ post.text|safe }}</h5></td>
                            </tr>
                        </table>
                    </div>
                </td>
                <td id="rightcol">
                    <div class="body">
                        <table>
                            <tr>
                                <th>
                                    <h4>Отклики (Всего откликов {{ responses.count }})</h4>
                                </th>
                                <th></th>
                            </tr>
                            <tr>
                                {% if responses %}
                                    {% for response in responses %}
                                        <tr>
                                            <td>{{ response.text }}
                                                <br> <strong>от {{ response.res_user }}</strong>
                                            </td>
                                            <td>
                                                {% if perms.PostBoard_main.change_response %}
                                                {% if response.status != True %}
                                                <a href="{% url 'response_accept' pk=response.id %}"> Принять </a>
                                                {% endif %}
                                                {% endif %}
                                            </td>
                                            <td>
                                                {% if perms.PostBoard_main.delete_response %}
                                                <a href="{% url 'response_delete' pk=response.id %}?next={{ request.path }}"> Удалить </a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                <td>
                                    <h7>Откликов совсем нет</h7>
                                </td>
                                {% endif %}
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>
        </table>
            <div class="col-lg-12 text-center">
                <hr>
                {% if post.to_reg_user.reg_user != request.user %}
                <button>
                    <a class="nav-link" href="{% url 'add_response' pk=post.id %}">
                        <h4><strong>Оставить отклик</strong></h4>
                    </a>
                </button>
                {% endif %}
                <button>
                    <a class="nav-link" href="{% url 'responses' %}">
                        <h4><strong>Посмотреть все отклики</strong></h4>
                    </a>
                </button>
                <br>
                <br>
                <a href="{% url 'posts' %}"> Верунться к объявлениям </a>
                {% if post.to_reg_user.reg_user == request.user %}
                <br>
                {% if perms.PostBoard_main.change_posts %}
                <a href="{% url 'post_edit' pk=post.id %}"> Редактировать объявление</a>
                {% endif %}
                <br>
                {% if perms.PostBoard_main.delete_posts %}
                <a href="{% url 'post_delete' pk=post.id %}">Удалить объявление</a>
                {% endif %}
                {% endif %}
            </div>
</body>
</html>

PostBoard/templates/post_edit.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}


{% block content %}
<h1>Редактирование поста</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  {{ form.media }}
  {{ form.as_p }}
  <input type="submit" value="Save" />
</form>
{% endblock content %}

PostBoard/templates/posts.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}

<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>

        {% block title %}
        Posts
        {% endblock title%}
    </title>
</head>
<body>
{% block content %}


    <h1>Доска объявлений</h1>

    <h6>Всего объявлений: {{ posts|length }}</h6>

    <h3> {{ next_sale|default_if_none:"Объявлений пока нет :(" }} </h3>

    <br>

    <button>
        <a class="nav-link" href="{% url 'search' %}">
            <h4><strong>Поиск по объявлениям</strong></h4>
        </a>
    </button>
    <br>
    <hr>
    {% if not request.user.is_authenticated %}
    <button>
        <a class="nav-link" href="{% url 'account_signup' %}">
            <h4><strong>Зарегистрироваться</strong></h4>
        </a>
    </button>
    <button>
        <a class="nav-link" href="{% url 'account_login' %}">
            <h4><strong>Залогиниться</strong></h4>
        </a>
    </button>
    {% endif %}

    {% if request.user.is_authenticated %}

    <button>
        <a class="nav-link" href="{% url 'responses' %}">
            <h4><strong>Все отклики</strong></h4>
        </a>
    </button>
    <button>
        <a class="nav-link" href="{% url 'subscriptions' %}">
            <h4><strong>Подписаться</strong></h4>
        </a>
    </button>
    <button>
        <a class="nav-link" href="{% url 'post_create' %}">
            <h4><strong>Создать новость</strong></h4>
        </a>
    </button>
    {% endif %}
    <br />

    {% if posts %}

        <table border="4" bordercolor="#000000" callspacing="0" callpadding="10" frame=Hsides rules=Cols width="100%" align="center">
            <br />
            <tr class="header">
                <th>Категория</th>
                <th>Автор</th>
                <th>Заголовок</th>
                <th>Время публикации</th>
                <th>Действия</th>
            </tr>
            {% for category in posts %}
            <tr>
                <td>{{ category.category }}</td>
                <td>{{ category.to_reg_user.reg_user }}</td>
                <td>{{ category.headline }}</td>
                <td>{{ category.time_in|date:'d M Y'  }}</td>
                <td>
                    <a href="{% url 'post_detail' pk=category.id %}"> Просмотр </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Новостей нет! Вообще нет!</h2>
    {% endif %}
    <br>
    {% if page_obj.previous_page_number == 1 %}
    <a href="?page=1">1</a>
    {% endif %}
    {% if page_obj.previous_page_number != 1 %}
    <a href="?page=1">
        Сюды
    </a>
    ...
    <a href="?page={{ page_obj.previous_page_number }}">
        {{ page_obj.previous_page_number }}
    </a>

    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">
            {{ page_obj.next_page_number }}
        </a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ paginator.num_page }}">
                Туды
            </a>
        {% endif %}
    {% endif %}
{% endblock content%}
</body>
</html>

PostBoard/templates/response_accept.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Приём отклика</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  <p>Принять "{{ object.text }}"?</p>
  <input type="submit" value="Accept" />
</form>
{% endblock content %}

PostBoard/templates/response_create.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}


{% block content %}
<h1>Отклик</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save" />
</form>
{% endblock content %}

PostBoard/templates/response_delete.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление отклика</h1>
<hr>
<form action="" method="post">
  {% csrf_token %}
  <p>Удаляем "{{ object.text }}"?</p>
  <input type="submit" value="Delete" />
</form>
{% endblock content %}

PostBoard/templates/responses.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Response
        {% endblock title%}
    </title>
</head>
<body>
{% block content %}

    <h1>Все отклики</h1>
    <h6>Всего откликов: {{ responses|length }}</h6>

    <form action="" method="get">
        {{ filterset.form }}
        <input type="submit" value="Найти" />
    </form>

    {% if responses %}
        <table border="4" bordercolor="#000000" callspacing="0" callpadding="10" frame=Hsides rules=Cols width="100%" align="center">
            <tr class="header">
                <th>Пост</th>
                <th>Время публикации</th>
                <th>Автор</th>
                <th>Текст</th>
                <th>Состояние</th>
                <th>Действия</th>
            </tr>
            {% for resp in responses %}
                <tr>
                    <td>{{ resp.res_post }}</td>
                    <td>{{ resp.time_in|date:'d M Y'  }}</td>
                    <td>{{ resp.res_user }}</td>
                    <td>{{ resp.text }}</td>
                    <td>{{ resp.status }}</td>
                    <td>
                        {% if perms.PostBoard_main.change_response %}
                        {% if resp.status != True %}
                        <a href="{% url 'response_accept' pk=resp.id %}"> Принять </a>
                        {% endif %}
                        {% endif %}
                        {% if perms.PostBoard_main.delete_response %}
                        <a href="{% url 'response_delete' pk=resp.id %}?next={{ request.path }}"> Удалить </a>
                        {% endif %}
                        <hr>
                    </td>
                </tr>
            {% endfor %}
        </table>

    {% else %}
        <h2>Откликов пока нет :(</h2>
    {% endif %}
    <br>
    <a href="{% url 'posts' %}"> Верунться к объявлениям </a>
    <br>
    {% if page_obj.previous_page_number == 1 %}
    <a href="?page=1">1</a>
    {% endif %}
    {% if page_obj.previous_page_number != 1 %}
    <a href="?page=1">
        Сюды
    </a>
    ...
    <a href="?page={{ page_obj.previous_page_number }}">
        {{ page_obj.previous_page_number }}
    </a>

    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">
            {{ page_obj.next_page_number }}
        </a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ paginator.num_page }}">
                Туды
            </a>
        {% endif %}
    {% endif %}


{% endblock content%}
</body>
</html>

PostBoard/templates/search.html
<!DOCTYPE html>
{% extends 'flatpages/default.html' %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Поиск
        {% endblock title%}
    </title>
</head>
<body>
{% block content %}

    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Найти" />
    </form>

    <hr>
    {% if search %}

        <table border="4" bordercolor="#000000" callspacing="0" callpadding="10" frame=Hsides rules=Cols width="100%" align="center">
            <br />
            <tr class="header">
                <th>Категория</th>
                <th>Автор</th>
                <th>Заголовок</th>
                <th>Время публикации</th>
                <th>Действия</th>
            </tr>
            {% for n in search %}
            <tr>
                <td>{{ n.category }}</td>
                <td>{{ n.to_reg_user.reg_user }}</td>
                <td>{{ n.headline }}</td>
                <td>{{ n.time_in|date:'d M Y'  }}</td>
                <td>
                    <a href="{% url 'post_detail' pk=n.id %}"> Просмотр </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Увы, ничего не нашлось :(</h2>
    {% endif %}
    <br>
    <a href="{% url 'posts' %}"> Верунться к объявлениям </a>
    <br>
    {% if page_obj.previous_page_number == 1 %}

        <a href="?page=1">1</a>

    {% endif %}

    {% if page_obj.previous_page_number != 1 %}
    <a href="?page=1">
        Сюды
    </a>
    ...
    <a href="?page={{ page_obj.previous_page_number }}">
        {{ page_obj.previous_page_number }}
    </a>

    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">
            {{ page_obj.next_page_number }}
        </a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ paginator.num_page }}">
                Туды
            </a>
        {% endif %}
    {% endif %}


{% endblock content%}
</body>
</html>

PostBoard/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />
                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}

    <a href="{% url 'posts' %}"> К постам </a>

{% endblock content %}